### ISSUE TITLE
Theme testing

### ISSUE THREAD

**Issue by Maikuolan** [phpMussel/themes#2]
Added a few lines of new code to the core script file based upon https://github.com/Maikuolan/phpMussel/issues/22; I'll commit these in a moment.

With these changes, I tested the themes, and they appear to work well; Looking nice. :-)

Attached below are some screenshots.

For comparison, using the default template, without any custom theme:
![default_template](https://cloud.githubusercontent.com/assets/12571108/9156297/ac6a91a2-3f07-11e5-904f-aac5374c1805.png)

Using the custom themes template, with the default theme:
![custom-base_colors](https://cloud.githubusercontent.com/assets/12571108/9156299/c6ea82e4-3f07-11e5-925e-bef2b3aeb659.png)

The "blue" theme:
![custom-blue](https://cloud.githubusercontent.com/assets/12571108/9156301/d7a924dc-3f07-11e5-9c33-a8208bfdd131.png)

The "subBlack" theme:
![custom-subblack](https://cloud.githubusercontent.com/assets/12571108/9156304/dd9a0f0a-3f07-11e5-858d-004cee043204.png)

**Comment by DanielRuf** [comment]
Awesome, this makes it much easier to use themes.

Should we add a forward slash after the curly brackets before the *.css? This prevents issues when people forget the slash at the end (double forward slash is internally converted to single forward slash as far as I know). So we do not have to check the occurrence of the slash at the end with PHP.

Sorry, oversaw this in my initial comment that an additional slash would be helpful in some cases.

http://stackoverflow.com/questions/10161177/url-with-multiple-forward-slashes-does-it-break-anything

http://stackoverflow.com/questions/27588091/do-browsers-ignore-slashes-in-urls?lq=1

**Comment by Maikuolan** [comment]
Good point. Yeah, I think we should. :-)

**Comment by DanielRuf** [comment]
I think we can close this issue, what do you think?

**Comment by Maikuolan** [comment]
Yeah, I think we can close it. Seems good.
